In [48]:
import numpy as np

Ejercicio 1

In [49]:
np.random.seed(42)
array_sample1 = np.random.random_sample((2,5))
array_sample1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [50]:
np.random.seed(42)
array_sample2 = np.random.random_sample((2,5))
array_sample2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [51]:
#Podemos crearlos utilizando la misma "semilla", el mismo número a partir del cual se generarán los números aleatorios. Se crea con seed().

Ejercicio 2

In [52]:
uniforme = np.round(np.random.uniform(0,10, size = (2,3,5)), 0)
uniforme

array([[[ 0., 10.,  8.,  2.,  2.],
        [ 2.,  3.,  5.,  4.,  3.],
        [ 6.,  1.,  3.,  4.,  5.]],

       [[ 8.,  2.,  5.,  6.,  0.],
        [ 6.,  2.,  1.,  9., 10.],
        [ 8.,  3.,  1.,  7.,  4.]]])

In [53]:
unicos_unif = np.unique(uniforme)
unicos_unif

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [54]:
binomial = np.random.binomial(10,0.3, size = (2,3,5))
binomial

array([[[1, 3, 1, 5, 2],
        [4, 2, 3, 3, 2],
        [6, 4, 5, 5, 3]],

       [[5, 1, 2, 1, 2],
        [3, 2, 4, 2, 2],
        [3, 1, 4, 1, 6]]])

In [55]:
unicos_bi = np.unique(binomial)
unicos_bi

array([1, 2, 3, 4, 5, 6])

Ejercicio 3

In [56]:
#Con intersect1d obtenemos un array con los elementos únicos que están presentes en los dos arrays.
np.intersect1d(unicos_unif, unicos_bi)

array([1., 2., 3., 4., 5., 6.])

In [57]:
#Con union1d obtenemos un array con los elementos únicos que están presentes tanto en el array1 como en el array2.
np.union1d(unicos_unif, unicos_bi)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [58]:
#Con union1d obtenemos un array con los elementos únicos que están presentes en el array1 pero no en el array2.
np.setdiff1d(unicos_unif, unicos_bi)

array([ 0.,  7.,  8.,  9., 10.])

Ejercicio 4

In [59]:
array1 = np.random.randint(1, 100, (80))
array1

array([88,  1,  8, 88, 63, 11, 81,  8, 35, 35, 33,  5, 41, 28,  7, 73, 72,
       12, 34, 33, 48, 23, 62, 88, 37, 99, 44, 86, 91, 35, 65, 99, 47, 78,
        3,  1,  5, 90, 14, 27,  9, 79, 15, 90, 42, 77, 51, 63, 96, 52, 96,
        4, 94, 23, 15, 43, 29, 36, 13, 32, 71, 59, 86, 28, 66, 42, 45, 62,
       57,  6, 28, 28, 44, 84, 30, 62, 75, 92, 89, 62])

In [60]:
array2 = np.random.randint(1, 100, (80))
array2

array([97,  1, 27, 62, 77,  3, 70, 72, 27,  9, 62, 37, 97, 51, 44, 24, 79,
       59, 32, 96, 88, 52, 62, 58, 52, 12, 39,  2,  3, 56, 81, 59,  2,  2,
       92, 54, 87, 96, 97,  1, 19,  2, 53, 44, 90, 32, 70, 32, 68, 55, 75,
       56, 17, 38, 24, 69, 98, 70, 86, 11, 16, 97, 73, 59, 70, 80, 93,  3,
       20, 59, 36, 19, 90, 67, 19, 20, 96, 71, 52, 33])

In [61]:
array1 = np.unique(array1)
array1

array([ 1,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 23, 27, 28, 29,
       30, 32, 33, 34, 35, 36, 37, 41, 42, 43, 44, 45, 47, 48, 51, 52, 57,
       59, 62, 63, 65, 66, 71, 72, 73, 75, 77, 78, 79, 81, 84, 86, 88, 89,
       90, 91, 92, 94, 96, 99])

In [62]:
array2 = np.unique(array2)
array2

array([ 1,  2,  3,  9, 11, 12, 16, 17, 19, 20, 24, 27, 32, 33, 36, 37, 38,
       39, 44, 51, 52, 53, 54, 55, 56, 58, 59, 62, 67, 68, 69, 70, 71, 72,
       73, 75, 77, 79, 80, 81, 86, 87, 88, 90, 92, 93, 96, 97, 98])

In [63]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 4,  5,  6,  7,  8, 13, 14, 15, 23, 28, 29, 30, 34, 35, 41, 42, 43,
       45, 47, 48, 57, 63, 65, 66, 78, 84, 89, 91, 94, 99])

In [64]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 2, 16, 17, 19, 20, 24, 38, 39, 53, 54, 55, 56, 58, 67, 68, 69, 70,
       80, 87, 93, 97, 98])

In [65]:
array5 = np.intersect1d(array1, array2)
array5

array([ 1,  3,  9, 11, 12, 27, 32, 33, 36, 37, 44, 51, 52, 59, 62, 71, 72,
       73, 75, 77, 79, 81, 86, 88, 90, 92, 96])

In [70]:
long1 = len(array1)
long1

57

In [71]:
long2 = len(array2)
long2

49

In [72]:
long3 = len(array3)
long3

30

In [73]:
long4 = len(array4)
long4

22

In [74]:
long5 = len(array5)
long5

27

In [76]:
long3 + long5 == long1

True

In [77]:
long4 + long5 == long2

True

In [78]:
long1 + long4 == long2 + long3

True

In [79]:
long1 - long3 == long2 - long4

True