Ejercicio 1.

In [1]:
import numpy as np

In [2]:
array1 = np.random.randint(1,15, (2))
array1

array([12,  7])

In [3]:
array2 = np.random.randint(1,15, (2,3))
array2

array([[ 2, 14,  1],
       [ 9, 10,  9]])

In [4]:
array3 = np.random.randint(1,15, (2,3,5))
array3

array([[[ 8,  1, 10,  4,  6],
        [ 9,  5,  5, 14, 12],
        [12, 14,  5, 11, 10]],

       [[ 1,  4, 14,  2,  4],
        [10,  4,  8, 14,  7],
        [14,  9,  2,  2,  5]]])

Ejercicio 2

In [5]:
np.random.random_sample






<function RandomState.random_sample>

In [6]:
np.array

<function numpy.array>

In [7]:
array1.ndim

1

In [8]:
np.ones_like(array2)

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
np.zeros_like(array2)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.empty(array1)

array([[4.04738577e-320, 1.77863633e-321, 0.00000000e+000,
        1.58276815e-316, 4.94065646e-324, 1.58276894e-316,
        1.58278119e-316],
       [1.18575755e-322, 6.93144708e-310, 4.24399158e-314,
        5.81021200e-321, 4.94065646e-324, 4.24399158e-314,
        1.03753786e-322],
       [1.58276934e-316, 6.93144830e-310, 6.93128705e-310,
        4.94065646e-324, 1.69759663e-313, 4.94065646e-324,
        1.58277487e-316],
       [1.58277526e-316, 1.18575755e-322, 6.93144295e-310,
        6.36598737e-314, 1.69759663e-313, 1.90979621e-313,
        3.18299369e-313],
       [0.00000000e+000, 1.58277843e-316, 0.00000000e+000,
        1.69759663e-313, 1.58277171e-316, 1.58277408e-316,
        1.58277764e-316],
       [4.94065646e-324, 3.39519327e-313, 3.18299369e-313,
        1.58277882e-316, 1.58279266e-316, 2.47032823e-323,
        0.00000000e+000],
       [5.58788245e-321, 1.58279266e-316, 4.94065646e-324,
        3.39519327e-313, 9.88131292e-324, 1.58276815e-316,
        2.47032823

In [11]:
np.empty_like(array3)

array([[[       21338680,               0, 140294074970032,
         140294076593712, 140294076020208],
        [140294076727216, 140294054252272, 140294073593200,
         140294053088592, 140294076596912],
        [140294076614256, 140294076591216, 140294076192816,
         140294076898288, 140294053070864]],

       [[140294076200432, 140294076019888, 140294076591024,
         140294076449456, 140294072877360],
        [140294076893488, 140294076460784, 140294076460848,
         140294076621616, 140294076613232],
        [140294076321136, 140294073927024, 140294076907376,
         140294076620144, 140294076595760]]])

In [12]:
def obtener_propiedades(array):
    num_dimensiones = array.ndim
    tamaño_total = array.size
    tipo_datos = array.dtype
    propiedades = {
        'número dimensiones': num_dimensiones,
        'tamaño del array': tamaño_total,
        'tipo de datos': tipo_datos,
    }
    return propiedades

In [13]:
obtener_propiedades(array1)

{'número dimensiones': 1,
 'tamaño del array': 2,
 'tipo de datos': dtype('int64')}

In [14]:
obtener_propiedades(array2)

{'número dimensiones': 2,
 'tamaño del array': 6,
 'tipo de datos': dtype('int64')}

In [15]:
obtener_propiedades(array3)

{'número dimensiones': 3,
 'tamaño del array': 30,
 'tipo de datos': dtype('int64')}

Ejercicio 3

In [22]:
matriz_identidad = np.array([[2,3,3],[4,5,6],[7,8,9]])
matriz_identidad

array([[2, 3, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ejercicio 4

In [23]:
array3

array([[[ 8,  1, 10,  4,  6],
        [ 9,  5,  5, 14, 12],
        [12, 14,  5, 11, 10]],

       [[ 1,  4, 14,  2,  4],
        [10,  4,  8, 14,  7],
        [14,  9,  2,  2,  5]]])

In [25]:
array3_ones = np.ones_like(array3)
array3_ones

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

Ejercicio 5

In [26]:
array2

array([[ 2, 14,  1],
       [ 9, 10,  9]])

In [27]:
matriz_identidad

array([[2, 3, 3],
       [4, 5, 6],
       [7, 8, 9]])

No se pueden sumar porque tienen filas diferentes

In [29]:
matriz_identidad2 = np.array([[2,5,3],[6,5,8],[2,8,9]])

In [31]:
suma_matrices = matriz_identidad + matriz_identidad2
suma_matrices

array([[ 4,  8,  6],
       [10, 10, 14],
       [ 9, 16, 18]])

In [32]:
multi_matrices = matriz_identidad * suma_matrices
multi_matrices

array([[  8,  24,  18],
       [ 40,  50,  84],
       [ 63, 128, 162]])

In [33]:
multi_matrices = matriz_identidad / suma_matrices
multi_matrices

array([[0.5       , 0.375     , 0.5       ],
       [0.4       , 0.5       , 0.42857143],
       [0.77777778, 0.5       , 0.5       ]])