Ejercicio 1

Las series son unidimensionales.
Los dataframes son bidimensionales, se componen por filas y columnas.

Ejercicio 2

In [40]:
import numpy as np
import pandas as pd

In [17]:
valores = np.random.randint(0,20, (7))
valores

array([17, 14,  6,  8,  5,  5,  8])

In [18]:
indices = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
indices 

['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

In [19]:
serie3 = pd.Series(valores, indices)
serie3

Lunes        17
Martes       14
Miércoles     6
Jueves        8
Viernes       5
Sábado        5
Domingo       8
dtype: int64

In [20]:
valores = np.random.randint(0,20, (7))
indices = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

diccionario_vacio = {}

for a, b in zip(valores, indices):
    diccionario_vacio[b] = a

print(diccionario_vacio)

{'Lunes': 19, 'Martes': 12, 'Miércoles': 11, 'Jueves': 10, 'Viernes': 10, 'Sábado': 19, 'Domingo': 1}


In [21]:
serie4 = pd.Series(diccionario_vacio)
serie4

Lunes        19
Martes       12
Miércoles    11
Jueves       10
Viernes      10
Sábado       19
Domingo       1
dtype: int64

In [22]:
serie4.shape

(7,)

In [23]:
serie4.dtypes

dtype('int64')

In [24]:
serie4.size

7

In [25]:
serie4.index

Index(['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado',
       'Domingo'],
      dtype='object')

In [26]:
serie4.values

array([19, 12, 11, 10, 10, 19,  1])

In [27]:
serie4['Lunes']

19

In [28]:
serie5 = serie4.loc[:'Miércoles']
serie5

Lunes        19
Martes       12
Miércoles    11
dtype: int64

In [32]:
serie6 = serie4.iloc[0:7:6]
serie6

Lunes      19
Domingo     1
dtype: int64

Ejercicio 3

In [47]:
array1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
array1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
dataframe1 = pd.DataFrame(array1)
dataframe1

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [50]:
lista_columnas = ['España', 'Francia', 'Italia']

In [56]:
cambio_paises = pd.DataFrame(dataframe1, columns = lista_columnas)
cambio_paises

España  Francia  Italia
0     NaN      NaN     NaN
1     NaN      NaN     NaN
2     NaN      NaN     NaN
3     NaN      NaN     NaN

In [55]:
df = pd.read_csv("data/medallas.csv", index_col=["País"])
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [62]:
tailandia = df.loc[['Tailandia']]
tailandia 

Unnamed: 0  Oro  Plata  Bronce
País                                     
Tailandia           7  132    175     278

In [61]:
china_iran = df.loc[['China', 'Irán']]
china_iran

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [73]:
china_iran_medallas = df.loc[['China', 'Irán'], ['Oro', 'Plata', 'Bronce']]
china_iran_medallas

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [86]:
india = df.iloc[[5]]
india

Unnamed: 0  Oro  Plata  Bronce
País                                 
India           6  154    202     315

In [84]:
paises_impares = df.iloc[1::2]
paises_impares

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

In [87]:
paises_impares = df.iloc[1::2, [1,2,3]]
paises_impares

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

In [88]:
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [93]:
oro_medallas = df[df['Oro'] > 200]
oro_medallas

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [107]:
oro_plata_medallas = df[(df['Oro'] > 200) & (df['Plata'] > 1000)]
oro_plata_medallas

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

In [108]:
oro_bronce_medallas = df[(df['Oro'] > 200) | (df['Bronce'] > 700)]
oro_bronce_medallas

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [113]:
df_borrado = df.drop('Unnamed: 0', axis = 1)
df_borrado

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [119]:
df_total = df['Total'] = df.sum(axis = 1)
df_total

País
China              6376
Japón              6112
Corea del Sur      4476
Irán               1122
Kazajistán         1084
India              1354
Tailandia          1184
Indonesia           982
China Taipéi       1056
Corea del Norte     912
dtype: int64