In [1]:
import numpy as np

Ejercicio 1

In [4]:
bidimensional = np.random.rand(5,3).round(2)
bidimensional

array([[0.2 , 0.01, 0.08],
       [0.35, 0.5 , 0.48],
       [0.5 , 0.3 , 0.54],
       [0.55, 0.72, 0.19],
       [0.38, 0.31, 0.31]])

In [5]:
bidimensional[0,1]

0.01

In [6]:
bidimensional[1,:2]

array([0.35, 0.5 ])

In [8]:
bidimensional[0::2,:]

array([[0.2 , 0.01, 0.08],
       [0.5 , 0.3 , 0.54],
       [0.38, 0.31, 0.31]])

In [9]:
bidimensional[bidimensional > 0.5]

array([0.54, 0.55, 0.72])

In [10]:
valor1 = bidimensional < 0.2
valor2 = bidimensional > 0.5
bidimensional[valor1 | valor2]

array([0.01, 0.08, 0.54, 0.55, 0.72, 0.19])

Ejercicio 2

In [11]:
multidimensional1 = np.random.randint(0,50, (2,5,3))
multidimensional1

array([[[10, 39, 38],
        [38, 27,  9],
        [19, 42, 14],
        [37, 17,  8],
        [17, 36, 31]],

       [[30, 13, 12],
        [ 5, 37, 45],
        [31, 49, 21],
        [22,  0, 16],
        [48, 34,  6]]])

In [12]:
multidimensional2 = np.random.randint(0,50, (3,2,5))
multidimensional2

array([[[35, 15,  1,  2, 26],
        [44, 35, 43, 44, 34]],

       [[24, 19,  7, 10, 33],
        [12, 23, 12, 13, 15]],

       [[22, 35,  2, 46, 40],
        [28,  7, 15,  0, 43]]])

In [13]:
def obtener_propiedades(array):
    num_dimensiones = array.ndim
    tamaño_total = array.size
    tipo_datos = array.dtype
    propiedades = {
        'número dimensiones': num_dimensiones,
        'tamaño del array': tamaño_total,
        'tipo de datos': tipo_datos,
    }
    return propiedades

In [14]:
obtener_propiedades(multidimensional1)

{'número dimensiones': 3,
 'tamaño del array': 30,
 'tipo de datos': dtype('int64')}

In [15]:
obtener_propiedades(multidimensional2)

{'número dimensiones': 3,
 'tamaño del array': 30,
 'tipo de datos': dtype('int64')}

In [16]:
sum_multi = multidimensional1 + multidimensional2

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

No se puede, porque el número de matrices es diferente.

In [20]:
#con método transpose
multi1_modify = np.transpose(multidimensional1, (2,0,1))
multi1_modify

array([[[10, 38, 19, 37, 17],
        [30,  5, 31, 22, 48]],

       [[39, 27, 42, 17, 36],
        [13, 37, 49,  0, 34]],

       [[38,  9, 14,  8, 31],
        [12, 45, 21, 16,  6]]])

In [26]:
sum_multi = multi1_modify + multidimensional2
sum_multi 

array([[[45, 53, 20, 39, 43],
        [74, 40, 74, 66, 82]],

       [[63, 46, 49, 27, 69],
        [25, 60, 61, 13, 49]],

       [[60, 44, 16, 54, 71],
        [40, 52, 36, 16, 49]]])

In [24]:
#con método reshape
multi2_modify = np.reshape(multidimensional2, (2,5,3))
multi2_modify

array([[[35, 15,  1],
        [ 2, 26, 44],
        [35, 43, 44],
        [34, 24, 19],
        [ 7, 10, 33]],

       [[12, 23, 12],
        [13, 15, 22],
        [35,  2, 46],
        [40, 28,  7],
        [15,  0, 43]]])

In [27]:
sum_multi2 = multi2_modify + multidimensional1
sum_multi2 

array([[[45, 54, 39],
        [40, 53, 53],
        [54, 85, 58],
        [71, 41, 27],
        [24, 46, 64]],

       [[42, 36, 24],
        [18, 52, 67],
        [66, 51, 67],
        [62, 28, 23],
        [63, 34, 49]]])