Ejercicio 1.

In [1]:
import numpy as np

In [7]:
array1 = np.random.randint(1,15, (2))
array1

array([ 4, 10])

In [8]:
array2 = np.random.randint(1,15, (2,3))
array2

array([[13, 12,  5],
       [ 5, 11, 10]])

In [9]:
array3 = np.random.randint(1,15, (2,3,5))
array3

array([[[ 3,  1, 13,  1,  5],
        [ 4,  4,  4,  7, 12],
        [13, 12,  6, 12, 13]],

       [[11,  8,  2, 10,  6],
        [ 5, 11, 10, 11, 11],
        [12,  2,  6,  3, 10]]])

Ejercicio 2

In [22]:
np.random.random_sample






<function RandomState.random_sample>

In [21]:
np.array

<function numpy.array>

In [20]:
array1.ndim

1

In [23]:
np.ones_like(array2)

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
np.zeros_like(array2)

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
np.empty(array1)

array([[7.64521479e-317, 0.00000000e+000, 1.50071887e-316,
        1.69759665e-313, 2.33419539e-313, 6.94932402e-310,
        1.50071728e-316, 3.76496994e-317, 1.69759668e-313,
        2.97079415e-313],
       [6.94932402e-310, 6.94947734e-310, 1.69759665e-313,
        2.33419539e-313, 4.94065646e-324, 1.50072400e-316,
        1.50072440e-316, 6.94947734e-310, 0.00000000e+000,
        6.15378782e-313],
       [7.00258613e-313, 6.15378779e-313, 6.94947727e-310,
        1.50072321e-316, 0.00000000e+000, 0.00000000e+000,
        6.94947618e-310, 6.94947618e-310, 1.69759666e-313,
        7.00258613e-313],
       [6.15378779e-313, 6.94947734e-310, 4.94065646e-324,
        1.50073389e-316, 1.69759666e-313, 2.54639497e-313,
        9.88131292e-324, 1.50073270e-316, 1.49026009e-316,
        1.49026246e-316]])

In [28]:
np.empty_like(array3)

array([[[           4593,               0, 140658983606064,
         140658985612720, 140658983612272],
        [140658983621920, 140658983612720, 140658986747440,
         140658986753648, 140658987453808],
        [140658986746416, 140658986746480, 140658986746608,
         140658986762448, 140658986746288]],

       [[140658986746352, 140658986746672, 140658986746736,
         140658986746800, 140658986746864],
        [140658986746928, 140658986746992, 140658986751344,
         140658986751408, 140658986763888],
        [140658986764048, 140658986751472, 140658986751536,
         140658986751600, 140658986751728]]])

In [29]:
def obtener_propiedades(array):
    num_dimensiones = array.ndim
    tamaño_total = array.size
    tipo_datos = array.dtype
    propiedades = {
        'número dimensiones': num_dimensiones,
        'tamaño del array': tamaño_total,
        'tipo de datos': tipo_datos,
    }
    return propiedades

In [30]:
obtener_propiedades(array1)

{'número dimensiones': 1,
 'tamaño del array': 2,
 'tipo de datos': dtype('int64')}

In [31]:
obtener_propiedades(array2)

{'número dimensiones': 2,
 'tamaño del array': 6,
 'tipo de datos': dtype('int64')}

In [32]:
obtener_propiedades(array3)

{'número dimensiones': 3,
 'tamaño del array': 30,
 'tipo de datos': dtype('int64')}

Ejercicio 3

In [ ]:
matriz_identidad = (2,3,3)